# create task
POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTkwNjY5MjYsImlhdCI6MTc1OTA2Njg5Nn0.C3Wao4e8RpgFvYQgJtsCCeyyxP-KT-vF98A8wwjCDSw

{
    "priority": "A",
    "title": "This is a title",
    "description": "This is a description"    
}
###

# get one task
GET http://localhost:8080/api/tasks/4
###

# get all tasks
GET http://localhost:8080/api/tasks
###

# get all task - filtered A
GET http://localhost:8080/api/tasks?priority=A
###

# get all task - filtered B
GET http://localhost:8080/api/tasks?priority=B
###

# get all task - filtered C
GET http://localhost:8080/api/tasks?priority=C
###

# get all task - filtered empty
GET http://localhost:8080/api/tasks?priority=
###

# atomic update one task
PUT http://localhost:8080/api/tasks/4
Content-Type: application/json

{
  "priority": "A",
  "title": "This is a title",
  "description": "This is a description"
}
###

# atomic update one task
PUT http://localhost:8080/api/tasks/4
Content-Type: application/json

{
  "priority": "A",
  "title": "This is a title"
}
###

# partial update one task
PATCH http://localhost:8080/api/tasks/4
Content-Type: application/json

{
  "priority": "B"
}
###

# delete task - OK
DELETE  http://localhost:8080/api/tasks/4
###

# delete task - NOT OK
DELETE  http://localhost:8080/api/tasks/444
###

# soft delete task - OK
DELETE  http://localhost:8080/api/tasks/5?soft=true
###