# create task
POST http://localhost:8080/api/tasks
Content-Type: application/json
x-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTkwODIyMDEsInVzZXJuYW1lIjoiQm9iIDEifQ.Dv4DROVJQSLIlO0PfvUKAYZTY_QZgVpJ6jyhyeS8b-A

{
    "priority": "A",
    "title": "This is a title",
    "description": "This is a description"    
}
###

# get one task
GET http://localhost:8080/api/tasks/15
x-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTkwODIyMDEsInVzZXJuYW1lIjoiQm9iIDEifQ.Dv4DROVJQSLIlO0PfvUKAYZTY_QZgVpJ6jyhyeS8b-A
###

# get all tasks
GET http://localhost:8080/api/tasks
x-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTkwODIyMDEsInVzZXJuYW1lIjoiQm9iIDEifQ.Dv4DROVJQSLIlO0PfvUKAYZTY_QZgVpJ6jyhyeS8b-A
###

# get all task - filtered A
GET http://localhost:8080/api/tasks?priority=A
x-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTkwODIyMDEsInVzZXJuYW1lIjoiQm9iIDEifQ.Dv4DROVJQSLIlO0PfvUKAYZTY_QZgVpJ6jyhyeS8b-A
###

# get all task - filtered B
GET http://localhost:8080/api/tasks?priority=B
x-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTkwODIyMDEsInVzZXJuYW1lIjoiQm9iIDEifQ.Dv4DROVJQSLIlO0PfvUKAYZTY_QZgVpJ6jyhyeS8b-A
###

# get all task - filtered C
GET http://localhost:8080/api/tasks?priority=C
x-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTkwODIyMDEsInVzZXJuYW1lIjoiQm9iIDEifQ.Dv4DROVJQSLIlO0PfvUKAYZTY_QZgVpJ6jyhyeS8b-A
###

# get all task - filtered empty
GET http://localhost:8080/api/tasks?priority=
x-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTkwODIyMDEsInVzZXJuYW1lIjoiQm9iIDEifQ.Dv4DROVJQSLIlO0PfvUKAYZTY_QZgVpJ6jyhyeS8b-A
###

# partial update one task
PATCH http://localhost:8080/api/tasks/4
Content-Type: application/json
x-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTkwODIyMDEsInVzZXJuYW1lIjoiQm9iIDEifQ.Dv4DROVJQSLIlO0PfvUKAYZTY_QZgVpJ6jyhyeS8b-A

{
  "priority": "B"
}
###

# soft delete task - OK
DELETE  http://localhost:8080/api/tasks/5?soft=true
x-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTkwODIyMDEsInVzZXJuYW1lIjoiQm9iIDEifQ.Dv4DROVJQSLIlO0PfvUKAYZTY_QZgVpJ6jyhyeS8b-A
###