# register user
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "Bob 2",
    "password": "bobo123456"
}
###

# login user
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "Bob 2",
    "password": "bobo123456"
}
###

# logout user
POST http://localhost:8080/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTkwNjY5MjYsImlhdCI6MTc1OTA2Njg5Nn0.C3Wao4e8RpgFvYQgJtsCCeyyxP-KT-vF98A8wwjCDSw
###