# register user
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "Bob",
    "password": "bobo123456"
}
###

# login user
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "Bob",
    "password": "bobo123456"
}
###